### ISSUE TITLE
SUUUUUUUU **** DE ******

### ISSUE THREAD

**Issue by ELJOKER900** [SweetSofiMC/DiffusionCraft#3]
PRECISAMENTE ME MORIA DE GANAS PERO SOLO ES PARA ESA NVIDIA !!!!!!!!!
ME CAGO DE TI POR TODAS ESAS COSAS Q YO QUERIA PROBAR Q TIENE ESOS REQUISITOS ALTOS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!q

**Comment by SweetSofiMC** [comment]
¡Hola! Lamentablemente así es como funciona el modelo de stable diffusion y no es posible bajar los requisitos. Añadí una breve explicación del porqué detrás de este límite y algunos recursos en caso de que quieras intentar algo, lamentablemente todo está en inglés porque hay muy poca información disponible en español.

Si no tienes alguna otra pregunta cerraré el issue en los próximos días.

**Comment by ELJOKER900** [comment]
hey ,¿ no crees q seria mejor hacer un difussion craft mas simple y que tiene un boton para hacer la imagen? ¿o darle una captura de pantalla para convertirla? si no lo modificare ya q pronto voy a hacer un projecto para eliminar roblox con python , pronto dire sus motivos , buena suerte

**Comment by XDOneDude** [comment]
> hey ,¿ no crees q seria mejor hacer un difussion craft mas simple y que tiene un boton para hacer la imagen? ¿o darle una captura de pantalla para convertirla? si no lo modificare ya q pronto voy a hacer un projecto para eliminar roblox con python , pronto dire sus motivos , buena suerte

a ver, si se puede usar con unos requisitos bajos solo que tardaria mucho en crear una sola imagen, ya lo probe con stable diffusion nmkd 1.5 y con 30 steps tardaba 2 minutos
